### ISSUE TITLE
feature request, static website snapshot

### ISSUE THREAD

**Issue by HosseinAlipour** [greatsuspender/thegreatsuspender#1049]
this is a great extension but I'm usually on the move and use mobile data that makes reloading very painful, It would be great if you could take a static snapshot of the tabs(removing all javascript code inside) and show it instead of "refresh or click to reload"; of course, it will be no longer an interactive website, but most of the time it doesn't need to be so.

**Comment by ganouri** [comment]
I was coming to suggest the same idea. It's a great way to improve the experience. It would avoid the user to reload the page in most cases.

Another great way to do it would be to take an HTML screenshot of the page, stripping all the js code, with a clear mention that the page will not work as intended until reloaded. It would still allow for scrolling without burning any resource.

**Comment by liamjohnston** [comment]
@HosseinAlipour @ganouri Just checking you know about the "Screen capturing" option? It might not be exactly what you're after (i.e. it's literally an image).

**Comment by ganouri** [comment]
thank @liamjohnston didn't know the feature :) I'll give it a shot, should help a lot. Well done!
