### ISSUE TITLE
Icon disappeared from Chrome menu

### ISSUE THREAD

**Issue by schda12** [greatsuspender/thegreatsuspender#1137]
Please complete the following information when submitting a feature request or bug report.
 * Extension version:7.1
 * Browser name & version:Chrome 83.0.4103.61 (Official Build) (64-bit)
 * Operating system & version:Windows 10 Pro 1909

And please also do a search for your request/bug before create a new one thanks!
Extension icon is not visible following system change.  Keyboard shortcuts work.  Other extension icons are displayed.

**Comment by greatsuspender** [comment]
It's possible you just need to 'stretch out' your extension icons area. It will automatically hide some icons if there is not enough room to display them all.

**Comment by schda12** [comment]
Thanks.  Chrome does a good job of hiding the ability to resize portions of the heading.  Once I found it and gave the icons more space, the icon appeared.

 

Meanwhile I’ve learned about the convenience of the keyboard shortcut.
