### ISSUE TITLE
Session management doesn't save full URL

### ISSUE THREAD

**Issue by Pascal666** [greatsuspender/thegreatsuspender#1140]
Please complete the following information when submitting a feature request or bug report.
 * Extension version: v7.1.0
 * Browser name & version: Google Chrome Version 83.0.4103.61 (Official Build) (64-bit)
 * Operating system & version: Microsoft Windows x64 Version 10.0.18363.836

Open https://bugzilla.redhat.com/show_bug.cgi?id=1811353 in a tab, save the session, then try to restore the tab.  You will get sent to https://bugzilla.redhat.com/show_bug.cgi instead.

**Comment by greatsuspender** [comment]
Hmmm.. I can't reproduce this. 
The url that is displayed on the suspended tab is missing the query string (on purpose), but unsuspending the tab takes me to the correct url, as does restoring the tab from session management screen.

**Comment by deanoemcke** [comment]
Hmmm.. I can't reproduce this.
The url that is displayed on the suspended tab is missing the query string (on purpose), but unsuspending the tab takes me to the correct url, as does restoring the tab from session management screen.

**Comment by Pascal666** [comment]
I am unable to reproduce this in v7.1.6.  My saved session from v7.1.0 still has the problem, but sessions saved under v7.1.6 appear to work correctly.
