### ISSUE TITLE
GitHub links on About page point to wrong repo

### ISSUE THREAD

**Issue by jschuur** [greatsuspender/thegreatsuspender#1142]
* Extension version: v7.1.6
 * Browser name & version: N/A (Chrome 83)
 * Operating system & version: N/A (macOS 10.15.5)

The About tab of the Options page still links to an old (or private) GitHub repo and issues page: https://github.com/greatsuspender/thegreatsuspender/issues

I think there was also a link to that issues page as part of the version upgrade process I just went through for the latest release too.

**Comment by greatsuspender** [comment]
That's actually the new repo link. It should be fixed now.

**Comment by jschuur** [comment]
Link works for me now.
