### ISSUE TITLE
Update Closed Open Suspended Tabs

### ISSUE THREAD

**Issue by marcwiest** [greatsuspender/thegreatsuspender#1143]
Hi there,

I just updated the add-on in Chrome to v7.1.6 and lost my tabs. The tabs where open and suspended. This included pinned tabs.

Thanks

**Comment by deanoemcke** [comment]
I'm really sorry about this. For whatever reason (I've tried really hard to determine exactly what) this happens to a handful of users during an extension update.
There is a pinned thread to help people recover from this situation: https://github.com/greatsuspender/thegreatsuspender/issues/526

I hope that helps you!

**Comment by marcwiest** [comment]
No worries. I still really appreciate you app. Thanks
