### ISSUE TITLE
Link to changelog

### ISSUE THREAD

**Issue by Pascal666** [greatsuspender/thegreatsuspender#1144]
It would be nice if the "The Great Suspender is about to get greater" page had a link to a changelog or what's new page.

**Comment by ludertal** [comment]
the release log is kind of changelog maybe, no ?

https://github.com/greatsuspender/thegreatsuspender/releases

**Comment by deanoemcke** [comment]
Yes. The release details were missing but I have since remedied that: https://github.com/greatsuspender/thegreatsuspender/releases/tag/v7.1.6

It was a very minor bugfix release so I did not bother detailing the changes on the update page within the extension itself.
