### ISSUE TITLE
What happened to version history? And donating?

### ISSUE THREAD

**Issue by jrynd** [greatsuspender/thegreatsuspender#1153]
Noticed the latest version removed the version history and donating. What happened?

**Comment by LeChatNoir666** [comment]
Great Q!
This App is abusing me with opening Tabs automatic with the Info, that it got better now, but don't tell us, "WHATS" better now!!!!
Maybe the extension got hijacked and now we have a security leak coz im not fun with an extension which opens Tabs over and over again!
Well... there are other open source Tab Suspender outside and maybe i will switch...

**Comment by greatsuspender** [comment]
Sorry for all the messaging. 
The first tab warning of a pending update is important as some users experience troubles with lost tabs and it gives them a chance to backup their tabs before going ahead with the update process.
The second tab reporting that the update was successful usually contains info on what has changed, although this time I didn't think there was anything noteworthy to report so I left it as the generic 'maintenance' messge.
For a change log of what is in the latest release see here: https://github.com/greatsuspender/thegreatsuspender/releases/tag/v7.1.6
