### ISSUE TITLE
Lost all suspended tabs after plugin update!!!

### ISSUE THREAD

**Issue by arseniihousedesign** [greatsuspender/thegreatsuspender#1155]
Please complete the following information when submitting a feature request or bug report.
 * Extension version:
 * Browser name & version:
 * Operating system & version:

And please also do a search for your request/bug before create a new one thanks!

last version v7.1.6
browser Chrome Версия 83.0.4103.61 (Официальная сборка), (64 бит)
windows 10

**Comment by deanoemcke** [comment]
I'm really sorry about this. For whatever reason (I've tried really hard to determine exactly what) this happens to a handful of users during an extension update.
There is a pinned thread to help people recover from this situation: #526

I hope that helps you, and sorry again :(
