### ISSUE TITLE
P L E A S E stop annoying us with your update information tab!!!!!

### ISSUE THREAD

**Issue by LeChatNoir666** [greatsuspender/thegreatsuspender#1156]
I love your extension but P L E A S E stop amnoying us with the information of an update!!!!

I want to update if ->I<- want and seeing my browser after letting it 3h alone with many new tabs opened with your update info is... well... you know!

EDIT: Oh, and... you wrote in your annoying update tab, that your extension is getting better...
I've searched in the Chrome Store and also here about WHAT's better now, but didn't found a breadcrumb of what's better now, so why not deliver some information instead of annoying us with opening Tabs over and over again???

Might my guessing right, that your extension is hijacked and now an security risk?

**Comment by deanoemcke** [comment]
This post pretty much mirrors a lot of the sentiment in this other recently created issue: https://github.com/greatsuspender/thegreatsuspender/issues/1147

Will close this as a duplicate.
