### ISSUE TITLE
Can the "Open link in suspended tab" option please be moved back into the right click menu instead of being buried in a submenu of the same?

### ISSUE THREAD

**Issue by Keslen-Keslen** [greatsuspender/thegreatsuspender#1157]
This comment was made in my name with content I never authorized.

All I'm really looking for is for the "open link in new suspended tab" to be moved back to the right click menu instead of being buried in a submenu.

Can that please happen?

**Comment by deanoemcke** [comment]
Yes, I'm not sure what's caused this sorry. There's another report (with screen captures) which I'll keep open and close this as a duplicate: https://github.com/greatsuspender/thegreatsuspender/issues/1145
