### ISSUE TITLE
Suspended tabs no longer become active after using 'reload all tabs' extension

### ISSUE THREAD

**Issue by cryssybee** [greatsuspender/thegreatsuspender#1161]
* Extension version: v7.1.6
 * Browser name & version: Version 81.0.4044.138 (Official Build) (64-bit)
 * Operating system & version: Windows 10

With previous versions of this extension I was able to use a 'reload all tabs' extension (Reload All Tabs (v4.2.0)) to easily reactivate tabs when several were suspended in the same window. 
This stopped working with the recent update. Now when I reload all tabs, the suspended tab placeholder page simply reloads. I now have to reload every tab individually, which is kind of tedious.

**Comment by ossilator** [comment]
why not just use the "unsuspend all tabs" menu point?

**Comment by deanoemcke** [comment]
The "unsuspend all tabs" command does seem to be what you are looking for.
Also, I don't normally change functionality to accomodate other extensions, as it tends to be a fairly niche set of users.
