### ISSUE TITLE
whitelist ignored by session restore

### ISSUE THREAD

**Issue by ossilator** [greatsuspender/thegreatsuspender#1162]
* Extension version: 7.1.something (didn't verify yet with the current one)
 * Browser name & version: chromium 81
 * Operating system & version: linux

when the session is restored during chrome startup, a bunch of tabs that are on the whitelist (various messenger apps) fire up in the suspended state and need explicit activation. afterwards, things work as expected.

i didn't check the effect of "open and suspend" of the built-in session manager.

**Comment by Luckz** [comment]
It is my understanding (from memory, how this API works) that the only workaround is activating the tabs one by one. Perhaps pinned tabs are always loaded on startup.

In my book code that loops through the qualifying tabs and takes turns making them 'active' with a delay would be silly. Pinning and unpinning them would be worse (potentially destructive towards the tab order as well).

**Comment by ossilator** [comment]
upon further thought, this is isn't related to TGS at all. chrome around v75 simply started to delay full activation of new tabs until they are foregrounded, and there is no way to configure that (any more).
