### ISSUE TITLE
Feature Request: Bookmarks Context Menu

### ISSUE THREAD

**Issue by thunduaga** [greatsuspender/thegreatsuspender#1165]
* Extension version: v7.1.6
 * Browser name & version: Chrome Version 83.0.4103.61 (Official Build) (64-bit)
 * Operating system & version: Windows 7 Home Premium x64

I sometimes save sessions "manually" by simply bookmarking all opened tabs to a bookmark folder.

It would be great if you could right click in the bookmarks bar, select a folder and have the option to "Open all tabs as suspended" + "...as suspended in a new window" 

that way i could resume my ridiculous 100+ tab "session" without causing my computer a heart attack. I understand TGS has its own session management that offers to open a session with all tabs suspended in a new window, though it would be fantastic if you could also have the context menu options available when right clicking within the bookmarks bar.

As a note, it appears no other extension/method offers this feature, TGS would be alone in this achievement.

Thank you for your support, time, and thank you for this extension.

**Comment by nfultz** [comment]
I don't believe the chrome extension API supports handlers on the bookmark bar. See also this [SO question](https://stackoverflow.com/questions/16288704/bookmarks-bar-click-event-listener-chrome-extension).

**Comment by thunduaga** [comment]
Wow interesting, thank you for the SO reference. Cheers,
