### ISSUE TITLE
Want to show the original capture image instead of default suspended  image.

### ISSUE THREAD

**Issue by sotayamashita** [greatsuspender/thegreatsuspender#1171]
Please complete the following information when submitting a feature request or bug report.
 * Extension version: 7.1.6
 * Browser name & version: Chrome & Version 83.0.4103.97 (Official Build) (64-bit)
 * Operating system & version: macOS Catalina

And please also do a search for your request/bug before create a new one thanks!

=======================

First of all. I appreciate your great work. However, I have an idea that would improve this ext.

### Problem
I think this extension is for people who open many tabs. In this case, at least I'll forget about what I open. I understand we can know the information from the URL but it is not intuitive for me.

### Possible solutions
![Group 2](https://user-images.githubusercontent.com/1587053/84618546-7a544480-af0d-11ea-84f9-d5188c088096.png)

Before suspending tabs, the ext takes a screenshot and show the image instead of default suspended page.

### Risk
If we would provide this feature, we need to take screenshots beforehand every time. It might be not good for performance and If we would store these images in browsers, It would occupy the storage of the browser.

Let me hear what you think.
Thanks in advance.

**Comment by sotayamashita** [comment]
I am trying to create a PR for it.

**Comment by ossilator** [comment]
you mean, like the "Screen capturing" combo box found near the bottom of the settings page?

**Comment by sotayamashita** [comment]
@ossilator Yes it is. Thanks
