### ISSUE TITLE
strange problems with the new chrome updated when you have many tabs (like 150)

### ISSUE THREAD

**Issue by Ilaem** [greatsuspender/thegreatsuspender#1192]
Please complete the following information when submitting a feature request or bug report.
 * Extension version: 7.1.6
 * Browser name & version: Chrome 84.0.4147.89 (Build ufficiale) (a 64 bit)
 * Operating system & version: Windows 10 1903

I have a lot of suspended tabs, Chrome does not allow resizing [in width] of the window (this only in window mode, no problem in full screen)

testing the problem I think it is the fault that for some reason Chrome MUST display all the icons of the suspended tabs created by this program creating a window that is much wider than the screen width,

> trying to shrink the window from the right, there is no effect.

> trying to shrink from the left, the window will quickly be moved OFF the screen from the right side...
**_(To grad the window go to the taskbar, move the pointer upon the Chrome icon waiting for the preview to appear, then right-click on it and select "maximize / fullscren" [sorry I don't have an OS in eng] and then just drag the window.)_**

if you divide the tabs into two windows with 70-80 each
resizing in width is allowed up to a certain (minimum) width which varies from how many tabs are in the window.

I honestly don't know if this problem is to be reported here or to Chrome since it appeared after updating it.

----   It appears that the problem has actually been resolved with the new Chrome update 84.0.4147.105 ----

**Comment by oboist-j** [comment]
The same issue after Chrome update to 84.0.4147.89 (Official Build) (64-bit)

**Comment by Ilaem** [comment]
Could anyone test if this is a Google problem by testing with the app disabled?
And by opening completely new tabs that have not been touched by the app.

Remember to make a back-up of the session, I tried in part and for some reason some tabs disappeared between the restart of Chrome,
in addition having a laptop (4Gb) and a desktop (6GB) of almost 10 years ago, if I try to do it without something to suspend the tabs the PC could explode ...

**Comment by ktivdv** [comment]
Happening here too. I have 100+ tabs open, and the browser window stretches way off the desktop. I can save my session and close the window, reopen the session, and the window will be sized correctly - but some actions seem to trigger the window being resized gigantically and subsequently cannot be reduced: 
1) I use ShiftIt to resize windows - maximising the window enlarges it outside of the screen. 
2) Going full screen on a youtube video, for example, causes the window to enlarge outside of the screen.

I will try saving the session and disabling the extension to see what the behaviour is, but I expect it's a chrome issue and not the extension...

**Comment by ktivdv** [comment]
> Happening here too. I have 100+ tabs open, and the browser window stretches way off the desktop. I can save my session and close the window, reopen the session, and the window will be sized correctly - but some actions seem to trigger the window being resized gigantically and subsequently cannot be reduced:
> 
> 1. I use ShiftIt to resize windows - maximising the window enlarges it outside of the screen.
> 2. Going full screen on a youtube video, for example, causes the window to enlarge outside of the screen.
> 
> I will try saving the session and disabling the extension to see what the behaviour is, but I expect it's a chrome issue and not the extension...

Interesting...although it was normal size, here's what the top-right corner of the browser looks like after disabling extension and restarting:

![Screenshot 2020-07-24 at 14 18 58](https://user-images.githubusercontent.com/19184901/88390544-c7eb8900-cdb8-11ea-939a-5f1682345796.png)

The tabs seem to go past the + add tab button. I tried maximising the window size with ShiftIt and the window stayed normal. Then I moved the window to my other monitor, and the window became enormous again. :(

**Comment by Ilaem** [comment]
It appears that the problem has actually been resolved with the new Chrome update.

**Comment by Ilaem** [comment]
It appears that the problem has actually been resolved with the new Chrome update 84.0.4147.105

**Comment by Ilaem** [comment]
It appears that the problem has actually been resolved with the new Chrome update 84.0.4147.105

**Comment by oboist-j** [comment]
Confirmed after the latest update Version 84.0.4147.105 works again
