### ISSUE TITLE
[Help] Push configuration settings with Group Policy

### ISSUE THREAD

**Issue by pullrequestluke** [greatsuspender/thegreatsuspender#1226]
Please complete the following information when submitting a feature request or bug report.
 * Extension version: v7.1.6
 * Browser name & version: Chrome, 85.0.4183.121 (x64)
 * Operating system & version: W10 (x64) / WServer

After founding out the existance of The Great Suspender I've pushed the extension to our test-user using Windows Group Policy.. Our test-user is able to use the extension but now I'm stuck at our next step... We're trying to push **configuration settings** through Windows Group Policy. 

I've found the settings but **where** can i define those settings in Windows Group Policy?

> Windows Group Policies
It is possible to force settings by defining group policies on Microsoft Windows.
The whitelist is stored internally as a string, with one URL per line.
The following settings can be defined:
SCREEN_CAPTURE (string, default: '0')
SCREEN_CAPTURE_FORCE (boolean, default: false)
SUSPEND_IN_PLACE_OF_DISCARD (boolean, default: false)
DISCARD_IN_PLACE_OF_SUSPEND (boolean, default: false)
USE_ALT_SCREEN_CAPTURE_LIB (boolean, default: false)
DISCARD_AFTER_SUSPEND (boolean, default: false)
IGNORE_WHEN_OFFLINE (boolean, default: false)
IGNORE_WHEN_CHARGING (boolean, default: false)
UNSUSPEND_ON_FOCUS (boolean, default: false)
IGNORE_PINNED (boolean, default: true)
IGNORE_FORMS (boolean, default: true)
IGNORE_AUDIO (boolean, default: true)
IGNORE_ACTIVE_TABS (boolean, default: true)
IGNORE_CACHE (boolean, default: false)
ADD_CONTEXT (boolean, default: true)
SYNC_SETTINGS (boolean, default: true)
SUSPEND_TIME (string (minutes), default: '60')
NO_NAG (boolean, default: false)
WHITELIST (string (one URL per line), default: '')
THEME (string, default: 'light')

**Comment by aciidic** [comment]
This is possible in v7.1.8 (download from source, it's not yet on web store)

See https://github.com/greatsuspender/thegreatsuspender/issues/1174#issuecomment-714548416

**Comment by pullrequestluke** [comment]
Great work and thank you for the heads-up. I'll close this case and waiting for progress in #1174.
