### ISSUE TITLE
Allow Google Analytics to be switched off

### ISSUE THREAD

**Issue by DanAtkinson** [greatsuspender/thegreatsuspender#202]
I would like to have the option to switch off your use of Google Analytics.

There is no mention of the fact that my use of the extension is tracked and there is currently no way to opt out of being tracked.

**Comment by deanoemcke** [comment]
This is a fair request. To clarify, information is only passed up once, on extension restart (install/upgrade etc) and it only passes up version number, and the value for some of the options (time to suspend, auto unsuspend etc).
To be honest, I haven't found the analytics all that useful so may just scrap it altogether. But allowing users to opt-out is a fair call. I'll try to implement this soon.

**Comment by wadkar** [comment]
+1 for scraping it altogether.

**Comment by weiweihuanghuang** [comment]
+1

**Comment by awkaiser** [comment]
+1 to removing GA or adding opt-out capability _before_ **stalebot** closes this 🤓

**Comment by superhero1** [comment]
+1

**Comment by SnIPeRSnIPeR** [comment]
+1

**Comment by wadewegner** [comment]
+1 to @DanAtkinson's comment. I learned about this from a colleague and was quite disappointed to learn this information is getting sent to Google Analytics.
